"""Initial Migration

Revision ID: e37539341c0c
Revises: 
Create Date: 2025-06-03 00:41:05.621640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37539341c0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('detection_date', sa.String(length=50), nullable=True),
    sa.Column('detection_time', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('violence_detected', sa.Boolean(), nullable=True),
    sa.Column('original_video_path', sa.String(length=255), nullable=True),
    sa.Column('result_video_path', sa.String(length=255), nullable=True),
    sa.Column('screenshot_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_history')
    # ### end Alembic commands ###
